stages:
  - "test"
  - "build"
  - "package"

default:
  tags:
    - "kubernetes"

variables:
  GO_URL: "https://go.dev/dl/go1.22.3.linux-amd64.tar.gz"
  GO_SHA256SUM: "8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36"

test:
  stage: "test"
  image: "harbor.maxiv.lu.se/dockerhub/library/golang:1.21"
  script:
    # The tests are limited to this directory for now.
    - "go test -v ./internal/..."

.package/rpm/bin-only:
  stage: "package"
  # image: "harbor.maxiv.lu.se/dockerhub/library/rockylinux:8"
  # dependencies:
  #   - "build"
  artifacts:
    when: on_success
    expire_in: "5 days"
    paths:
      - "RPMS/*"
  script:
    - |
      if test $CI_COMMIT_TAG != ""; then
        VERSION="$CI_COMMIT_TAG"
      else
        VERSION="0.0.$(date +%s).$CI_COMMIT_SHORT_SHA"
      fi
    - "dnf install -y rpmdevtools rpmlint systemd-rpm-macros curl"
    - |
      curl -L https://go.dev/dl/go1.22.3.linux-amd64.tar.gz -o /tmp/go.tar.gz
      echo $GO_SHA256SUM /tmp/go.tar.gz | sha256sum -c
      if test $? != 0; then
        echo "Bad checksum. stop"
        exit 1
      fi
      cd /opt/
      tar xvpf /tmp/go.tar.gz
      export PATH=$PATH:/opt/go/bin/
      go version
    - "rpmdev-setuptree"
    - "mkdir -p /usr/src/build/haproxy-spoe-auth-$VERSION"
    - "cp -r ./ /usr/src/build/haproxy-spoe-auth-$VERSION/"
    - "tar --create --file /usr/src/build/haproxy-spoe-auth-$VERSION.tar.gz -C /usr/src/build/ ./haproxy-spoe-auth-$VERSION/"
    - "cp /usr/src/build/haproxy-spoe-auth-$VERSION.tar.gz ~/rpmbuild/SOURCES/"
    - 'cat packages/rpm/haproxy-spoe-auth.spec | sed -e "s/__PKG_VERSION__/$VERSION/" > ~/rpmbuild/SPECS/haproxy-spoe-auth.spec'
    - |
      cd ~/rpmbuild/
      rpmbuild -bb SPECS/haproxy-spoe-auth.spec
    - "cp -rf ~/rpmbuild/RPMS/ $CI_PROJECT_DIR/"
    - 'echo "Saving in registry"'
    - |
      __FILES=$(find $CI_PROJECT_DIR/ -name '*.rpm')
      for file in $__FILES; do
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $file "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/haproxy-spoe-auth/$VERSION/$(basename $file)"
      done

package/rpm/bin-only/RL8:
  extends: ".package/rpm/bin-only"
  image: "harbor.maxiv.lu.se/dockerhub/library/rockylinux:8"

package/rpm/bin-only/RL9:
  extends: ".package/rpm/bin-only"
  image: "harbor.maxiv.lu.se/dockerhub/library/rockylinux:9"

container-image/build:
  stage: build
  variables:
    BUILDAH_CACHE: "true"
    BRANCHES_TO_INCLUDE: "master"
  trigger:
    strategy: depend
    include:
      - project: kits-maxiv/kubernetes/k8s-gitlab-ci
        ref: "0.6"
        file: "Docker-build.gitlab-ci.yml"
  rules:
    # package from production branch when changed or tagged
    - if: "$CI_COMMIT_BRANCH =~ $BRANCHES_TO_INCLUDE && $CI_MERGE_REQUEST_IID == null"
      changes:
        - "**/**"
        - ".gitlab-ci.yml"
    - if: "$CI_COMMIT_TAG"
    # If you need to run the pipelines for Merge requests, add:
    - if: "$CI_MERGE_REQUEST_IID != null"
