stages:
  - "test"
  - "package"

default:
  tags:
    - "$RUNNER_TAG"

variables:
  GO_URL: "https://go.dev/dl/go1.23.1.linux-amd64.tar.gz"
  GO_SHA256SUM: "49bbb517cfa9eee677e1e7897f7cf9cfdbcf49e05f61984a2789136de359f9bd"

test:
  stage: "test"
  image: "docker.io/library/golang:1.23"
  script:
    # The tests are limited to this directory for now.
    - "go test -v ./internal/..."

.package/rpm/bin-only:
  stage: "package"
  artifacts:
    when: on_success
    expire_in: "5 days"
    paths:
      - "RPMS/*"
  script:
    - |
      if test $CI_COMMIT_TAG != ""; then
        VERSION="$CI_COMMIT_TAG"
      else
        VERSION="0.0.$(date +%s).$CI_COMMIT_SHORT_SHA"
      fi
    - "dnf install --allowerasing -y rpmdevtools rpmlint systemd-rpm-macros golang curl"
    - |
      curl -L $GO_URL -o /tmp/go.tar.gz
      echo $GO_SHA256SUM /tmp/go.tar.gz | sha256sum -c
      if test $? != 0; then
        echo "Bad checksum. stop"
        exit 1
      fi
      tar xvpf /tmp/go.tar.gz -C /opt/
      export PATH=/opt/go/bin/:$PATH
      go version
    - "rpmdev-setuptree"
    - "mkdir -p /usr/src/build/haproxy-spoe-auth-$VERSION"
    - "cp -r ./ /usr/src/build/haproxy-spoe-auth-$VERSION/"
    - "tar --create --file /usr/src/build/haproxy-spoe-auth-$VERSION.tar.gz -C /usr/src/build/ ./haproxy-spoe-auth-$VERSION/"
    - "cp /usr/src/build/haproxy-spoe-auth-$VERSION.tar.gz ~/rpmbuild/SOURCES/"
    - 'cat packages/rpm/haproxy-spoe-auth.spec | sed -e "s/__PKG_VERSION__/$VERSION/" > ~/rpmbuild/SPECS/haproxy-spoe-auth.spec'
    - |
      cd ~/rpmbuild/
      rpmbuild -bb SPECS/haproxy-spoe-auth.spec
    - "cp -rf ~/rpmbuild/RPMS/ $CI_PROJECT_DIR/"
    - 'echo "Saving in registry"'
    - |
      __FILES=$(find $CI_PROJECT_DIR/ -name '*.rpm')
      for file in $__FILES; do
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file $file "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/haproxy-spoe-auth/$VERSION/$(basename $file)"
      done

package/rpm/bin-only/RL8:
  extends: ".package/rpm/bin-only"
  image: "docker.io/library/rockylinux:8"

package/rpm/bin-only/RL9:
  extends: ".package/rpm/bin-only"
  image: "docker.io/library/rockylinux:9"

container-image:
  stage: "package"
  image: quay.io/maxiv/ci-image-builder:v24.03.13
  script:
    - buildah-build
    - buildah-push
