stages:
  - "test"
  - "build"
  - "package"

default:
  tags:
    - "kubernetes"

test:
  stage: "test"
  image: "docker.io/library/golang:1.21"
  script:
    # The tests are limited to this directory for now.
    - "go test -v ./internal/..."

# build:
#   stage: "build"
#   image: "docker.io/library/golang:1.21"
#   artifacts:
#     untracked: false
#     when: on_success
#     expire_in: "1 days"
#     paths:
#       - "./build/haproxy-spoe-auth"
#   script:
#     - "mkdir build"
#     - "go build -o ./build/haproxy-spoe-auth ./cmd/haproxy-spoe-auth"

package/rpm/bin-only:
  stage: "package"
  image: "docker.io/library/rockylinux:8"
  # dependencies:
  #   - "build"
  artifacts:
    when: on_success
    expire_in: "5 days"
    paths:
      - "~/rpmbuild/RPMS/*"
  script:
    - |
      if test $CI_COMMIT_TAG != ""; then
        VERSION="$CI_COMMIT_TAG"
      else
        VERSION="$CI_COMMIT_SHORT_SHA"
      fi
    - "dnf install -y rpmdevtools rpmlint"
    - "rpmdev-setuptree"
    - "mkdir build/haproxy-spoe-auth-$VERSION"
    - "cp -r ./ build/haproxy-spoe-auth-$VERSION/"
    - "tar --create --file build/haproxy-spoe-auth-$VERSION.tar.gz -C build/ ./haproxy-spoe-auth-$VERSION/"
    - "cp build/haproxy-spoe-auth-$VERSION.tar.gz ~/rpmbuild/SOURCES/"
    - 'cat packages/rpm/haproxy-spoe-auth.spec | sed -e "s/__PKG_VERSION__/$VERSION/" > ~/rpmbuild/SPECS/haproxy-spoe-auth.spec'
    - |
      cd ~/rpmbuild/
      rpmbuild -bb SPECS/haproxy-spoe-auth.spec
